version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  worker:
    build: ./backend
    command: celery -A celery_app worker --loglevel=info -Q parse,analyze,report,priority
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  flower: # Celery task monitoring UI
    image: mher/flower:1.2
    ports:
      - "5555:5555"
    command: celery flower --broker=redis://redis:6379
    depends_on:
      - redis
